name: Append files together

on:
  push:
    branches: ['main']
    paths:
      - 'files/**'

jobs:
  append_files:
    name: Appends file extension files 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: true  # Ensures credentials are available for push
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: python -m pip install --upgrade pip setuptools wheel
    - name: Runs code
      working-directory: ./
      run: python append.py
    - name: Commits to repo
      working-directory: ./
      run: | 
        git config --global user.email "sundaresh.sankaran@gmail.com" 
        git config --global user.name "SundareshSankaran" 
        git config --global user.password ${{ secrets.NOTHINGIMP }}
        git add .
        git commit -a -m "Add new file by append.py" || exit 0
        git push
      